### PR TITLE
begin mlc package

### PR DESCRIPTION
**Pull request by brozonoyer**
@mboratko I'm beginning to work on a `multilabel_classification` package parallel to `graph_modeling`, and I've tried to mimic the setup for `graph_modeling.generate` to read the mlc datasets in arff format into python dicts and pickle them. However, I'm trying to figure out how/where to create a second `setup.py` file that would allow me to use `multilabel_classification` as a package from within the same repo. I make use of @dhruvdcoder's [`ARFFReader`](https://github.com/iesl/box-mlc-iclr-2022/blob/main/box_mlc/dataset_readers/arff_reader.py) which also requires allennlp to be installed, and I'm also not sure whether that would conflict with the current dependencies.

Just wanted to share these updates in case this is the wrong way to do things before I take them too far -- I would appreciate any help/comments/suggestions on the design choices for this. In addition to `graph_modeling` and `multilabel_classification` I was envisioning `collaborative_filtering` and `probabilistic_modeling` subpackages to span the gamut of tasks for my ablation study.

### CODE REVIEW

**Comment by brozonoyer** [comment]
I got to this point after adding allennlp into `requirements.txt`, updating `setup.py` and rebuilding; however I'm still getting version errors that prevent me from running to completion:
```
(box-training-methods) brozonoyer@morris box-training-methods % multilabel_classification generate mlc-dataset --indir /Users/brozonoyer/Desktop/IESL/data/box-mlc-iclr-2022-data/cellcycle_FUN --dataset_name cellcycle_FUN --num_labels 500 --outdir ./data/mlc/
Traceback (most recent call last):
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/bin/multilabel_classification", line 12, in <module>
    sys.exit(main())
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/brozonoyer/Desktop/IESL/box-training-methods/src/multilabel_classification/generate/__main__.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/Users/brozonoyer/Desktop/IESL/box-training-methods/src/multilabel_classification/generate/__main__.py", line 51, in mlc_dataset
    write_dataset(outdir, **mlc_config)
  File "/Users/brozonoyer/Desktop/IESL/box-training-methods/src/multilabel_classification/generate/__init__.py", line 19, in write_dataset
    mlc_module = import_module("multilabel_classification.generate.mlc")
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/brozonoyer/Desktop/IESL/box-training-methods/src/multilabel_classification/generate/mlc.py", line 2, in <module>
    from .arff_reader import ARFFReader
  File "/Users/brozonoyer/Desktop/IESL/box-training-methods/src/multilabel_classification/generate/arff_reader.py", line 23, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/allennlp/__init__.py", line 11, in <module>
    import transformers, spacy, torch, numpy  # noqa
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/transformers/utils/versions.py", line 120, in require_version_core
    return require_version(requirement, hint)
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/Users/brozonoyer/opt/anaconda3/envs/box-training-methods/lib/python3.8/site-packages/transformers/utils/versions.py", line 49, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.11.1,!=0.11.3,<0.13 is required for a normal functioning of this module, but found tokenizers==0.13.1.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

**Comment by dhruvdcoder** [comment]
You don't need to add `allennlp` as a dependency. In the arff_reader.py, there's a method called `read_internal()` which does the reading for the dataset stored in arff file format. I would suggest just copying that function and its children (functions it calls) into your code and write the rest of reading pipeline yourself. The only dependency this would bring in is `liac-arrf`.

**Comment by brozonoyer** [comment]
Just did a lot of refactoring, taking a break after I was able to successfully run the refactored code with the following command:
```
box_training_methods train --task graph_modeling --data_path ./data/graphs/balanced_tree/branching=2-log_num_nodes=12-transitive_closure=False/ --model_type hard_box --dim 8 --epochs 5
```

🦃 Issues that need to be addressed:

- [ ] cleanup messy imports
- [ ] implement task-specific `eval_step` and use it inside a generic `EvalLooper`. Currently I have a rather generic `TrainLooper` and  a graph-modeling-specific `EvalLooper` both sitting in `box_training_methods/train_eval/loopers.py`
- [ ] decide on API for `models` and task-specific `model_heads`. Currently the models' forward methods expect paired node indices representing graph edges (or negative examples), and return either an embedding or an energy function. Maybe just simplify to return box embeddings of node indices? 
- [ ] so far I've kept all the losses under the `graph_modeling` subpackage. Currently the losses' forward methods expect exclusively graph data as inputs. I'm guessing this could fly for multilabel classification if we view it as graph modeling in the label taxonomy _and_ the instance-label relations... but would we have problems when we move on to probabilistic modeling and collaborative filtering? Should I move `losses` to a top level like I did `models`? 
- [ ] The top-level `train` method in `box_training_methods/train_eval/__main__.py` currently has both generic click options (e.g. `data_path`, `epochs`) and also a few graph-modeling specific options (e.g. `--undirected / --directed`). Could I somehow move the graph-specific options down inside the task-specific `train_eval.py`, to decorate the `setup_{training_data,model}` methods invoked by the top-level `box_training_methods/train_eval/train.py`? Is there a simpler way to nest this functionality given my refactoring?
- [x] @dhruvdcoder do we have a reader in place to read the label taxonomy `hierarchy.edge_list` or `hierarchy_tc.edge_list`? I'm assuming it's one of the readers under your repo's [hierarchy_readers](https://github.com/iesl/box-mlc-iclr-2022/tree/main/box_mlc/dataset_readers/hierarchy_readers)?

cc @mboratko @dhruvdcoder

**Comment by brozonoyer** [comment]
Command for multilabel classifcation:
```
box_training_methods train --task multilabel_classification --data_path /Users/brozonoyer/Desktop/IESL/data/box-mlc-iclr-2022-data/cellcycle_FUN --model_type hard_box --dim 8 --epochs 5
```

**Pull request merged**
